import { cookies } from "next/headers";
import { GigRadarBoard, type SpotifyConnection } from "../../components/GigRadarBoard";
import { getGigRadarData } from "../../lib/gigRadar";
import { isSpotifyStoreConfigured, readSpotifyAuth } from "../../lib/spotifyAuthStore";
import { isValidTrainingRadarSession, TRAINING_RADAR_SESSION_COOKIE } from "../../lib/trainingRadarAuth";
import { redirect } from "next/navigation";

export const dynamic = "force-dynamic";

const NOTICES: Record<string, string> = {
  connected: "Spotify connected.",
  disconnected: "Spotify disconnected. The stored token was removed.",
  denied: "Spotify authorisation was declined.",
  error: "Spotify connection failed.",
};

function notice(status?: string, reason?: string): string | null {
  if (!status) return null;
  const base = NOTICES[status];
  if (!base) return null;
  // The reason codes are generated by our own callback, never reflected from
  // Spotify, so they are safe to show.
  return reason ? `${base} (${reason})` : base;
}

export default async function GigsPage({
  searchParams,
}: {
  searchParams?: Promise<Record<string, string | string[] | undefined>>;
}) {
  const cookieStore = await cookies();
  if (!isValidTrainingRadarSession(cookieStore.get(TRAINING_RADAR_SESSION_COOKIE)?.value)) redirect("/");

  const params = (await searchParams) ?? {};
  const status = typeof params.spotify === "string" ? params.spotify : undefined;
  const reason = typeof params.reason === "string" ? params.reason : undefined;

  const storeConfigured = isSpotifyStoreConfigured();
  let connection: SpotifyConnection = {
    connected: false,
    spotifyUser: null,
    connectedAt: null,
    storeConfigured,
    notice: notice(status, reason),
  };

  if (storeConfigured) {
    try {
      const stored = await readSpotifyAuth();
      if (stored) {
        connection = { ...connection, connected: true, spotifyUser: stored.spotifyUser, connectedAt: stored.connectedAt };
      }
    } catch (error) {
      // Report the store being unreachable rather than rendering "not
      // connected", which would invite a pointless reconnect.
      connection = {
        ...connection,
        notice: connection.notice ?? `Spotify token store unavailable: ${error instanceof Error ? error.message : "unknown error"}`,
      };
    }
  }

  return <GigRadarBoard data={await getGigRadarData()} connection={connection} />;
}
